### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Nomen3sT** [ZalaPanda/redmine-time-spender#4]
Hi Adrian,

I hope you're doing well. I would like to ask for something.
Is there any chance to implement some new functions, like creating new issues from app?
I really liked to use this extension to record my spent time on projects but our management shuffle things up and now we should create new issues for every task what we do. 
Thank you in advance!

Regards,
Norbert

**Comment by ZalaPanda** [comment]
Ok, so basically your feature request is now implemented.
It took more time as I expected and there are some limitations:
- You can assign new issues to yourself or noone but you can't select other users from a list. Why? Because the Redmine API. The [Users](https://www.redmine.org/projects/redmine/wiki/Rest_Users) endpoint requires admin privileges.
- Similar situation with the [Custom Fields](https://www.redmine.org/projects/redmine/wiki/Rest_CustomFields). It is not possible to get proper details about these fields (multiple/possible options/etc.) without admin rights. You can edit these fields but the implementation is not bulletproof.  
  And also there is this little checkbox too:
  ![image](https://user-images.githubusercontent.com/26068527/210187160-1e6f2967-6657-41c7-87d2-a2123d9e848e.png)
  If this is checked then the field will be used in every project but the [Projects](https://www.redmine.org/projects/redmine/wiki/Rest_Projects) endpoint forgots to mention the field. Maybe I should create a new issue about this on [redmine.org](https://www.redmine.org/projects/redmine/issues).

By the way this new release is currently waiting for the code review and then it will be installed automatically. If you want you can try it out before the release. You need to:
1. download the [.zip](https://github.com/ZalaPanda/redmine-time-spender/releases/download/v1.3.0/redmine-time-spender-1.3.0.zip) file from the latest release
2. extract it somewhere on your computer
3. open `chrome://extensions/` in your browser
4. enable **developer mode** (its a toggle switch in the top/right corner)
5. click on the **Load unpacked** button and navigate to the folder with the extracted files
... and done. Or you can wait for the code review, it is up to you.

**Comment by ZalaPanda** [comment]
Forget it. The code review is complete. Just update your chrome extensions and you can use the new version.
